### ISSUE TITLE
Backup Plugin fehler

### ISSUE THREAD

**Issue by Pflegecraft** [ophian/additional_plugins#2]
Beim ausführen des Serendipity Backups Sichern bekomme ich folgende Fehlermeldung
`Warning: Undefined array key "dirs" in /home/users/pflegecraft/www/blog/plugins/serendipity_event_backup/serendipity_event_backup.php: 872.
Administrative Login Error Warning only - not seen by visitors! Send us a note what happened where and when, please.`

**Comment by ophian** [comment]
Danke für die Meldung! Fix ist online. 
Available mit Spartacus je nachdem wann die letzte Synchronsation stattfand.
Mitte kurz melden und bestätigen ob OK, damit ich oder du das issue zumachen kann.

**Comment by Pflegecraft** [comment]
Jo jetzt läuft es dankeschön
