### ISSUE TITLE
500 Error Shoutcast Plugin

### ISSUE THREAD

**Issue by Pflegecraft** [ophian/additional_plugins#3]
Hallo ich habe einen Fehler gefunden sobald das Shoutcast Plugin aktiv ist bekomme ich beim Admin Panel 500er Error meldung.
Laut Fehlerlog datei folgender Eintrag:
`[Wed Nov 24 20:33:55.929123 2021] [proxy_fcgi:error] [pid 953:tid 140068040161024] [client 162.158.203.8:23510] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function ereg_replace() in /home/users/pflegecraft/www/blog/plugins/serendipity_plugin_shoutcast/serendipity_plugin_shoutcast.php:101\nStack trace:\n#0 /home/users/pflegecraft/www/blog/include/plugin_api.inc.php(992): serendipity_plugin_shoutcast->generate_content()\n#1 /home/users/pflegecraft/www/blog/include/functions_plugins_admin.inc.php(165): serendipity_plugin_api::get_plugin_title()\n#2 /home/users/pflegecraft/www/blog/include/admin/plugins.inc.php(673): show_plugins()\n#3 /home/users/pflegecraft/www/blog/serendipity_admin.php(162): include('...')\n#4 {main}\n  thrown in /home/users/pflegecraft/www/blog/plugins/serendipity_plugin_shoutcast/serendipity_plugin_shoutcast.php on line 101', referer: https://pflegecraft.de/serendipity_admin.php
`

**Comment by ophian** [comment]
Oh Danke.
Das ist ein sehr altes Plugin .. never touched without some cosmetics. The function `ereg_replace` was set deprecated  in PHP 5.3.0 and completely removed in a later version.
Kannst du in Zeilen 101 und 102 die beiden Vorkommen mal mit `preg_replace` ersetzen und schauen ob es damit klappt, am besten am lebenden Beispiel eines shoutstreams?!? Die beiden Vorkommen sollen alles vor `<body>` und alles nach `</body>` ersetzen bzw leeren. Wenn es dann alles ohne weitere Fehler ginge würde ich das Plugin updaten.
Braucht man es wirklich in der heutigen Zeit?

**Comment by ophian** [comment]
Fixed with 8e189449c6711c8e3f89120b85a3bac43df7035e. Please reopen if still an issue.
