### ISSUE TITLE
Gästebuch fehler meldung im eingeloggten zustand

### ISSUE THREAD

**Issue by Pflegecraft** [ophian/additional_plugins#4]
Wenn ich noch eingelogt bin und auf das Gästebuch zugreife bekomme ich folgende Fehlermeldung:
Warning: Undefined array key "paginator" in /home/users/pflegecraft/www/blog/plugins/serendipity_event_guestbook/serendipity_event_guestbook.php: 1231.
Administrative Login Error Warning only - not seen by visitors! Send us a note what happened where and when, please.

Was soll das heißen?

**Comment by ophian** [comment]
Das bedeutet das hier auf eine uninitialisierte Variable zugegriffen wird und du als Administrator (und auch nur du) darüber informiert wirst und sie hübsch gleich melden kannst.
Und siehe da: Update ist online. Danke!
