### ISSUE TITLE
Google Analytics Problem

### ISSUE THREAD

**Issue by Pflegecraft** [ophian/additional_plugins#5]
Hallo wenn ich Google Analytics einbinden möchte bekomme ich folgende Fehlermeldung auf meiner Hauptblogseite:
`Warning: Undefined array key "path" in /home/users/pflegecraft/www/blog/plugins/serendipity_event_google_analytics/serendipity_event_google_analytics.php: 184.
Administrative Login Error Warning only - not seen by visitors! Send us a note what happened where and when, please.
Warning: Undefined array key "path" in /home/users/pflegecraft/www/blog/plugins/serendipity_event_google_analytics/serendipity_event_google_analytics.php: 184.
Administrative Login Error Warning only - not seen by visitors! Send us a note what happened where and when, please.
Warning: Undefined array key "path" in /home/users/pflegecraft/www/blog/plugins/serendipity_event_google_analytics/serendipity_event_google_analytics.php: 184.
Administrative Login Error Warning only - not seen by visitors! Send us a note what happened where and when, please.
���[sG� �|���23&w�@�q�H�H]F�$��5����@�ݘ�"Ϝ�����<�9��؈��g?�i�O旜̬��ƅ�-q�������̬�̇_�|t��=6����W�ִ�}f��k����C|�z�����(�ޥ�Tx[�i�?��h�Y�y ����<��ϚV����j�Z���j��V4���[X�l�sMh�l3C��[_c�y�7���g��7G��VM>ʂ,�[��!�^���� QU�2��|�6�O�,Nj�G���C�`�� ;e���{��YG�n�ݺ][l�$��I�d�V��� 7}~��F� DАji������$��YZi&�|�~��a��6����_�k���EDs��|x�)��\4�����S���^ ��y�$�j��M�5�vK��V�&F�zI��q�QG�_D�sp]̥��3���� �� =�s�ȃF����f �SS�B�%��Z�O轮�&��&���|��Q "p���3z�]k��dh�n�P^|i����U⍲`�E@'р��?���dk�]�@Y���*˰�i)�7�b�y���� V<Njv�a�����!`n�A4�3Ss'v� E�Ut�s G�s��<�B��C@�|�}�F���OƏ�0�yo�6蓥 �Q^��H�╟զ#�e���0�l@F���|���_/6?�*,�J ]��N�e�&�q�Y��~�~][�ܲ��Y�g�hr��yr�$��KN5(W��̭�I0 ��U��������뢶�4s$\���:_T�ͱ�$�T��#����E���waް��pm���PfXqyc�D� ����Փ���]7�G�'翤��WA���`x����yc�6�,s���?6k�n�ajF��4:����?����7Na��h��.?�c\��*�c���~%\K��wKv�Mz�Go�^Ͱ�1G�|�`"m��ͱ�`��� ż3X�|ȣ��n����� qX7Q��(OXD�q@��4����,x�Q��&N���`w�[c<��Gl���@�Y˧i�z �` ��4��g>�6�I=�F���_��f;|A�@�b� ��'v��˰��Sl�'D�f�|=C�" A�O`����,S�A��V�E�/� >��c�Q�H�h�hB`�m�:�z�:�[5A�m\����Y��۝}�L�e�z�Ro�ɉ�(���}���a�i�����L߱�nM!_E��7�H �Ѐ���X"o�u�o�L�}�w���b�y*�Q ��b�Vz]7�@u&Hg�<��ʯ�l7Aj`}���������T����� �e�-���@k0쀇!�����������p�"�C`p���̘!\��t� M�q� ����W\�A��h6Ɂ����V�,D3�*��d�0���P͐��rf����;�ˎ��xH��h�������ӱ���Zִ�R۫lK,�8=���O����'amc��x��A��;֎G�$�f}�����[�v����=����`<G�)�F��K,!�����n�O8� �� =�Ƨ�t�%��F*yg�i\6�b_�f����1l��14�����fb��v�9O2_�ӋG����L��ӣ���џXn���i���7�����wk�\�&�� � E)�b���+�.-k[m�bu��A�O��~f��M��)�C�k������V���X���=�a��ζw��A�@4 �Ee!��K���N���� �N���O�C�;c� �mf���u��Q����*�U�@�])/�<�u����:�$x���S��L��t���׶��8�Wʀ��!t�>FI8�����F'�xk��7=b�x� � ���`An0�!��¿��T���s���WU9�*�� � ն�?�ܭ�lQ�ɂ;����6�����`\�RCV�;,*�$~p/��.d��>լָژ��ˊ�U�Z�9.��U,�5�5���.�c�Ue'e�j)��覬(;Qu�uA��:ו����r�^P�*:��m,C���!8d� �������k����a�v�$`���U��a���n6LS�7����{-J��-�s�P�xC��d�Q;�8Ȼ �4�e<�Ã>�u��ƅ ����I����kpy��0�F�hM�����b���׍���6�N�^Zwg���"6/X$)�d.-�#�[(��z��>�^G-�3�,oK��4_d1����� !JJ+��p���g7w fa#[��/Z�컴����˃m�5��{@�S@����v&Я�~��H�g�ċF\�f>��/��V��ь#C���R#�q/�h��kDý��1]�R2pt� J'����i g(��G�ALb�m��6�a6@ D��4���w[�*O���q`i�ʵg�:��������n��ڏ��d�; ��~�v��� !��B�l��&�,P�vx���>ǏIG��Y.?Ms0�m�X,�FRwP�C�1��:{ʃm0�����DX��"B$�֠H������i���Xҿ��d�d�b��9�Ls����aDf$PSŧ ����.��_Ǧ�̡��zJv��RO����&}��"���)�BjZ�rm�f��V��0 6^ېfB��1Y��WI�MW0��� �:�'�:�1$�� ��_�d�Ȫ�J���WD�V�t����(���8D$o��~ȅI�C���.���Ea&��Ax�[����c��Dw@0��Zgo"�4lf-�G��{g�^�Fh���@��hd�DR���p���M����V����d#/�!�ǅ�����4VD��Dۯw럫��Ҟ�I�<%&�8t���ڕ�4aE�-V�xm�%6���!��-U{�]��_ﮦ��ݥh�(�m˪�����=��J4pYS�QT�h� *( �X1KPͪ��n�+ͫ�j�ne��8C��>T͌�CT���S/Oq�-GR�){)*W�Wjك(UZǊ�Z~��|X5zTj����?�&�f?|1w|ts�}G��Rs� J�-�F���8��ǠE$H� �bdҏ�B~�PE���Fvex��_�W;�;,P=gur�;��r�$���< F�>� ��a2������d9Ꮵ�/����a�O�ۓ���g��G?Ma�Ƴ�8hJ3t�������;{ώ�N��u�P���J6dk��ֶԯ[��^Wo�ǦRo��[p��n���m��g�*��V�n�.*�E��Le��J���)z�tVT�t5C�l�CŠb�,��Z�� ����J�*NWX�Z˯�X�v�|G.>���\�Vm��@ٸ,V���K�ī��jU�IY��~������O�K��W��n�Zzm���G��4�Z�� �k�F���6)��|��c&�7S�qd�ݩ�B@���y��{��9�B��I,nz$���J�S�RG\��UFb���lo���-nȉ��y�N Z�q|d���M���o���0�!���Ai�C�V���S�X�`<�E�ƹ� "{{��N"���G���NM�)�oek b�� ��Q���$��G�I�[& ,jtF���+t�G_��A���O��n��Y�j�hW8���<{ۢ����ʺUCr�J0,T�p�՚�;xu]���e�Uz��z楪�'��n��sWJ�ѺC��hiV]{6��a�18�nJ�j��=_*yV��w�ku��F��3��0��cT#J<�ȇQ¼:����u>�F�/B����s������Z1��@��xKy[cN���4��}a손�1�? ~��Gx��KQg�x���� �xz ݄��@a���g���QIg�yx�K�No{l�~�|"�Y�yx��p} ������#l�:�!a��'�Q)4*�6�D8��9��o��p��$9���zf"t_rHU��)�d�_�3{qv�E'U9l$��C���p!�ғ�]�SE���e)�sv��/��;3��#T�/o����ě��"�0���p$ٙ�_"'�Ԗ. 0a�P�(\��"E��F\�I� 0 � 8](��@�������{���8G�BM��."��4�a(��%Z���tk������]�v]�~���vA|l���ޮ!�.� ����!�xVE�>��~=������0w�����m}�����V�>���Ф="Hɠ2bP�$��lqN��dR�uz���K\�v]�U^��)�xR�|t��Ŋў�V�)�,�0�n� ������7ۻ���Z�� ^�����XE(�h�!�֎80�W lP����� �@����of}���?�]]ٕ��-�7�~(��$���>MB�E�3��� �]9����j"���|\KI�����$��b\�X�{D�j�G�I�WڦR�i�X1����2����y��Z�{ �J��*�-����E��]�P ��՚��[�\���eՊv�8J;#*vF(�hgDE��2�R�ƈ_,���h����h�.�0^j����zf�;�@6�����)���끁N��8�����\�# �l��� }U�R�~�(�Fh� ɻ��Y)��ޞ�GAb���J������cf_��� MG�EfyZ ڱP��$��w��%f�B�L�1��a�V�s4N�En��(��0���N#�}���a��d7z�C'���������o9�j��јxctEj�X;H�ڄ�I����)�Gbgl<��9��o?�x~��.���B+��N�H�{��ѦT��ìU�H԰Ae��֛5��� �aZ;�<~���]:���%�V�v��{�z��CϏ��vc����ޚ�A��;������6�c:�ދ���֩"�d�e�X1�|$�����t���h�� �z^�[3t�Lc����z�P�9�i)I��n�!�)Ƣ�0 ����y�8D�%��� ]��D� }y���Z/n�a�<���xf����?�0�н;L���%�ΰ�N�U�P[ Arŀzx�#��x��ᵦ��&�ͅ�d�&��|�bHr��8��q���a�t^9��Ev�.�u��r�bF�������H�S�tXu�f �#�Z��J��"�sa��[di0.�](imz�u��brs�VjG���y/N蔥�WXE��`�#�az2(La��+�jݨ�M�)pI�p�@0��ҕ�^'�e;R�2u]o@����ŭ����i�`?5j����跖�"����e '� Q�$PF��ot����K�YǠO�O�Q��9���76�f���:6��p�eCB������ް��m�G�c�[�-��c� ��a�u��E�nX��,�u�����z�1YѲ(�ۭz�,�����oeI�,��_��� �c��4�3%[�xŲ� ǩ�Z���o�߶�0����Z�mʟ��ů�G�m��e��T�ew�CL '�lY��EH�zQrL�n�@�E��V�[�V���G.�ΰD��'@ۮ��N�:�G�H��ߢ#�H�P�v�lޭ z�iZ��i~�:fvt\��t\���]*Z6�u�EX\hF�6�v���8�F(�Am�M�l .P+ � ՎC�OMl��u͍�4����r���q�i#t�Lu��� @ e���5��Tt�\˟0,�x���S���Vٮ����v�-L�ն �L�j�0�@Q�d�O �hC�v� �T*dA��%& =`��3�iV�4.��E״�9�� P㚲-zl����nY����6)L}h�D�E������na �; (���6 ���1@,ö�bj�&ΔY��n#���&��$*�d �Ѧ�=����e1-b��O���E�^,?@1�apLP�ME�E�!>RtS�&V���@צ��,�k�h .����e ��g�PtAN-Ǣ*P�[�Q�л�hH�a#�ʎZ�P����K( Ԣ�b���0�j���`�%��u }� ��%v ��.�E���(-��9�*�/�um ���S� ����L����ES0!�S�����L���$�$�Zp�X�X�k"�c�jJ��=/Z<1Ԅ����k"j�m���p2��m$C���n��9(�h�� E�J�x%,�A�|��C=�ԣ>�������:�t�@�d[@,�Z HҼ�\6�QȒ�I�R.��r5���kUM�X��$B���j����7%94K ��*ک���B)�T��zk1~����e��Z��B���j��}�*��k}o����$��e-�IЗO���w�)��RG��ɪ���}V�1Z_T�;S�����2{�ȡ���gj�̋��s����j�e&�9c� ���N73?�@��"��~�a�~��5Po���kMam�l藀5B��$�H!��֫ Xs C`�Ҭ�g�5Mօ�U敦��@n{nd�E�.pfAo�xE��-���o����j�\��rD�x�6VH��t$���f�E�+�z9�V9��ixj]H?�!��\z�iԬ�{�Jޘ.FIA��ǈ��ʬ_�����>��M�f��&�uSv~��u�^�m����k�Z=�C������rO@�Cn����C^����G�θ������[L�=I�<�=[��8M����Bލ�� AZ�-N�R�pQ�J�o@iE>���a��� {�3� ��ck�9����xg�a�<$ƢpDb^z�� Wx�.�9���.E�F|4����aw���t<����N�4xm��{�i����6�&�xm(B��,>�����&��5�YC��+q��a���9�c_Z�Q��T�JJHQ��;�g���}T�'�ⲽ,V���__�I?�?i��I�W�X� ��[�0]����|Nݻ�9u�����a>�FN� ��$^�5�` �L��/%ޅ��w��Ju�l�F���M�+ݍ�/��k�٪���,��=K��ٳ�6���=�Be4��4K��NK���"��-^�k^z�����u����]�&��c-�SW �=���vU 8��ξi8��p��Cj�o����I&|`�(�{���=�4H2 �&�����S�os}s���ۏ�Ӽ[Fɛ�४�h��Yv)+��m�7e��n0�E�S��^�rLܝ�)�Qv�! �&����Ȕˁ��F�Cs��r�ym� �w|���)[xE� )�\�4��2_�~q�>�e���N�+��"�&��My2����}�����f�@�� �9.��L_7������4!P;�po ;^*��d!#� �Ó��@����$�"�y�`Q����t�W��f�y��5ϔ��P-���!�J�p#�����c���� ��VW%����]�_�˹������!Â)@�!��7��{2�>����f_aN�_���Qy���"Y���ګ����7��W��4y�^;��E���-4�dr��W������V�T�<�1s!E�P�%_�p��cOc��Hu�+(b/�;�H/��%��G^8J%E�l�؈\5"� �ԉ���D�.�®X� ۋ�i�a�F��f"����.Iu詊r���\Q��@R7)nA*���P<��b�a?g4�{Q���J�Z|�2П�^�:�W��:�< ��9Q0 `WM�s�����I�𴛠t�r �Y����Ћ|Bd��PcPL����!���!^�I�6� Ő1�)2�.OcL?��R��<�k'H��B��ט�S����0R��+"�'�q���G�9�K��a]���~b�}L$+�6��wRR��:� A���E��p�,M�(��{�a��*|�A>�L�)�����b����D0���\��~2�BLK�XА8��h�+f�Sy��<6��w�vD,�\y���e4��$���Ar�����DQ�C��p���'Y��7����<�����0ؒ[I�}����6���?l@S��W���6���Ç �U��1 ��q��S^�;;�W�u��N��b��ű��$�W����o2���[��.���OV���K�~�-���hg�I�rT2��Z*(x�]/��<��d�*�/&h��KI�=K�4��Q�i������`VԾ�TG?I��AZP����������o;�3��}��9f>�;m˷1��`��q2U�G�D�t�Q���L��e�����G�C��d��Jpߋr�<�~R�1��R��9IWI]uFJ��2�=dn��S8lO��PO�ԭF���Foe����,��z�|����BpG��X�gf�e<�)�r���� ��9R�T��`<���b "�bs�������`/�U�(��v�H�c�w8eJhG�Do�O@ԧ0db+�i�B��u��0VR �^� ����g��Iw��������{�Eo�l�r�E ��:�����R�za��I��� + �2RUn&AkNJ"���쮨'�@s]f�r������W:�Z��mqi9�C�s?� �[>C���kɌ�D�F��tKi"@#�Kv�^��<�Q���v���0�`�#>L�1Nu�d���w��ζ�r��0��"�e����3�G�ak�U���$����e�wC�B�c�9@���l��X$s�l7l�([S ���!��g��}��$�j��6�<k���R�jvF��TL�A0�Hz c`�)T F�����]���b������!��$��~T�3)��xz/�2)1�ۅ����ܢm �]eaܛL�XN�a�ٛ���~�~�s�nq��6��?5�����R���>>p�c���${V��6�v�r��]T,���,D%4��T�������勣g��_?'��s='v��� �U��u-�������=W�Z(�TVN���LV�}�k�H�*���b��GD2e�#Y�?���!�E�eEف�[1T=)c�b%Xլ�W�VR�WK+y�������G>�v���ڽ�����[8�����O;wy<�h��W�z��S-ɇ�y4=�x2�5҃�vm�VGoW����yN�����������I� B�h7+BG9ȍE�o�e0�gg�Q�r�]!JE�w�K��Dj�A�Q� �B#�r��+�& *�&R[a�rT�ޡ��6���p�JU��H�OD�bya�p�n��0e��4Bw�*� J$y��y"GM�>�*���~ ��B�]d�~�=Ą8)����㿮\Y���=vؓ��'�X�A�k�fV3n?aX|�/0i~~:�G |�@p��XoQ������ ��=4�z�(U�J�Xѫ9`�S,J�b�XQ�Ø.m2��7SY��*�+�h�*iL+: �|�?��ܑ�\��܂�w��sgZ�]*y����Qj�Bh���ؘJ��Ҷr���0� ��?��}����fX�֬�~"��3�:;��sj�9�~@p �FRɣ�4�8�:7y�H�z�5e�B�3�u&i� ��=�yr� �q:`�?ZRӴ��8|=��D����9x??�Ҟ�I������� Q�=�ve=)E�-��W��{,(7Q�,�%K�hF��}��r0�=\����%��+�uW�V�gy��!K��b���NY4, e�X^��?<����H2ز����tS�~�?�0~G�����U"�-�אT�JB7�PB7�]�h$�Dj_3�X�^k�zf|s�q�=2쎥/ę{/q�sğr4����\�&қ1��( ���a�r��s�.�t�32 �jr.6*,�h�Fk�ѐ�=��t; g��K�h��@��{B�E�k �@x=�uF1gvaUC{�V��-xN��%� սH�:����fak|£�0��!$}E^��B!ΧP���z_䏤c&9ϥf%�<|~����Hָ�j+Lj,�َ,V�u�f5� yV�4* Cy�f��r"�w�(Wl���S�]���QV��W#�7,:*+�^T�j]�q���fm�I��즬]����6�^�rم�Z��`.$P�(�IH��)_��L4|+��TT��*-�uY}�b߳����aa���N����'�K�����-j�we����ai�;�皼ۯ����{��6 ��� 9��e��7�(('��d�&�7�>2��S�Tzc�����Ta}�� :���s�\<a����cN�[1f3��}��n�%�6��?`<�%�0{�H��� N�8��x&O��)\����9��H��Q�"V.H��Y����txW��z \5�r T�8� �HG?���<����c����%3�Dd��aD�طf��>G� �]�˔L��A҇Qs���u�}(P(�Wh�A��� ��]K�p*#ݠC��$�K�|�l*ca(X�1]�E_÷| � )�v9FGG��G��\���^CL�-2�#�t����[�c��~��p ,4tN�.���=�1�ةGΐh��)�J��y#�ƾZ8 k��&f0��x=�K�+U�ɟ ���5t��MF�d����8��˅�^\�[%�%_����B��9H8C$�2���,,la31څ�/,����_O�.Н�mt(� ��<̾f;U�ί?? ��ϰ����c�������tU�����{x�P���u^�>����~o�yXу�<_ �yP�����~��j]�����RSvVT~Q�>��gݍ�g]��]���\���C��C[�� ��IcT_C� ��?Y�0���{L�Ǿ1����}SM f۾ �-3�~h���:��#j���� ���%�� C�)6�J��<�B̓�M�'���1� ^��[}x�/+�:я�g*���EQy�P^[|���6����$�N��i�k�"!���O�幖��4f�E+!�F�����a=����k��M$7��L�*E�ړ$�Lx���Hy^�b����O�1�� %�ľ��v7,�x���ٕ+��L8����l�KfW{y�Oh�??݌2��A(^t��^�a��t�ARC �G���I�����(;���B'�^9�ld��!F�@�|[\M�Li���)���$F�'��E��%:'z,qT�^��4eo&�oRvpEx���ΐ��y}�'�H� &Xt<P�cfo��x��#�,�8� ��K��Ao����q��[H�!��EB�V *�����;jр�fA���C4��B��<���+�(�yc�LD��F\�aO�(�] �^��>���a�z�ѭ��^�8�&�.�Ԣ i谢}u�TC3��e�2�b�E�aĒ���v����G���X5�d�1��Br��$AGo��t������$A3�adAd�f��TY�:�|�)K�V{��Cf�d�mJ]oMߠ�՝� Qo� g]%���KXx���U�M��`3��Iɴ��*�U3�:PEmʻ� 4��5LI�4LTW�+\����:��k�®�T���+�6\��K�hI�E��˾:Y୦[��2��t����e�^7�i�� L��08�I�U�������~��m��ln��lu���&�}����|��l�n�Pښ�D{��/��u��bG5L]�1��|��~qk��?�1@4`� 7k}�~kI�(� ���#�P���I��J���O�L��Y+r;�i�4���`&O�ֱ����"��w��[n��ۘ�ڱ�-ÖEL����-��7ݲh� �a��n�h�c�m��rLV�,��!�m��]�}�ŷ��Z�Eկ�RU���SR�&�w�@ ��f77��jU��_^��m������mʟ��ů�G���e��T�ew�CL '�lY���c��}E��V�[�V���G.�ΰD��'�Jo�&�u��T�`�EG������[�&)7(;�M�R��I�қ��ݹ�KE�v1߹�",.4�[����8�F(�Am��;���@���&T;�>5�"s�c�����՛Xnb[@�i`�v�N��nb��8���8Z�&��EG̵� sa�2��GH0>���xl��N��l��Ym��`�V �iň`A����p�64m��0�+@�B Yb��d�v�g(Ӭ�i0\�)& ��ᾘC(�5�)�J�EXÀ�v�-��|~�&"��m�(�h�s�-��na �; (���6 ���1@,ö�bj�&ΔY��n#���&��$*�d �Ѧ�=����e1-b��O���E�^,?@1�apLP�ME�E�!>RtS�&V���@צ��,�k�h .����e ��g�PtAN-Ǣ*ˀ&��e��EC2�VvКH��^Bi�����Ԅ)WC��C/1`�X_ Ȱh�S�Ì�M�Į�p��SE�e�3�R�e#��� ���#~ �a v����S�h &p*��r\�)8`v�Ę�@�C�Q�tM�b��^Mɷ�'��@�'"�����M�B����N��~��d���@�m�3�mb^��]�o��e!ȟ�}�G�zԇ��T���T��.H�l�%U�I�WÕK���\1 Yr=)T��V`Z�F5r��i+��D(�]WMq����$�fI!�]E;U���9(�A�_��e��KԵ"S���+�-[�v���r�e�Ϲ\˭/�ݝ�v��S���A�FC߬"H�*�\��ǹ����i�"��2����O��P���b�vX��e ������ZSX�.�%`̓P�3�3RHm���*�F�X�4k�YfM�u!�C�y���.�۞���a����R�v+�IS�Ǽ��N�Zi�4;����C��\V�"���|ӷ��s�Z.he9��<�i+$�Y:�� XG��"��m�w���4<��?�Őn`.��4jV�׽�t%oL �� ��cD�ie�/]Lw`H�g�}�Uz�);�c�a/��U=/��ڽV��P!lF�j.����[����p<-ŏ�qQ# !ŷ< �I�0`䗷zȯ��Bx�?�;7��r����U�lZԬ�xB^wQ�zQ.��U�b�����nߍ�}���N�7�`���]���e�G{��ő&�i)G�m^��;�>�Ż*��3��rcoi�qd�ǭ��S�Gtb��:���;~��qF�?3�1�hٔ�� Z�a3�`'�(P�5L[�Eo`��P:�bb`��P���:�r��LS���kl�R�������s���Py��* x�����g/�O�j���Vk[�Tߧ�uK#���a*�g�f�;ҫ{X>�eߕ�����G��K0��=�{���)Zj`4�x�m�mݴ�M�h��-�ҿ[!�6�a�47$D,\�i��^BQ�󬯵�`�^� ֫�MT��R%|W(+G��)�E������^�1�8� /n��%,���?�����9������w��;�hLk_��睊�9^�ƻx��x������e��5yX@x�}�+�,�h`,@~��4����&1��Q,J�� Ņ�w]((�ȯh�J��Ĺqڀ��ȋ�Bd���!F�@������L �6Ǽ�t�3z�g��bَ1}t��-�� �$��\w Ţ����>;�SP±�2�8���|��6�aF��DpÉ��?���Q����L#'�҇����D��R��ʝ{9�.܋�@�~y�ZW�~_V��W�'���T�O+^�WRި/k*W�U劽��Z��ʕD��v �W�X��j�|��o�Uq6�۪`W�a5�B}��ܣ/���m����T�'���i��ƚ�Wܕ�ƽC�����Q���J�<�x]Z{�2ৗ��d]N�-HB Y%���(늋�S�0h��7j��TZ����|��_�4�:2��,��oZ�������<դU� I���Q]/]��j_;]�U�UU�x �K���R6n�u�c5��DEF|}�fS���\Q�9�")�U��#��&����{-F�ZU�'ʫ��\���`��k�nk��S7�n.uߒ�y�����[�'�%����Y��͋��Wŷs���<��Io�A��K9w��'f�L�,��O�1H�#!��d҅*���$�'�o��G�#�>�]�Cs�ʔ��J���L�$y $�joy�%� fF���*k{A�L�J_hS���%��K��]4kX� �-�m��Tx�����H0^V�������1"�8�>����:�Apm�c��Z.�����ᒦV4�c�L�>���=2iM�Ph�0"M�Yroeu_�hm�u~�{3"�{=�}?�)��S�K� ��I���';Z�u,�i�ݖ�2=�C=������2�q�b�s�/ ^�w��e�=,1�h� aL��z7���{��) �VZ�4H'�2���a�bL��i�� �*�c(s��*⛭%�;*��"RYe�,[��l=}������r�s'p��qM�%�"�u�32����%v=p��,���!b_�͋��R�NP�l\cy^����7K�UD^�ޠ!�`��2w �J�f"����D��,F��y�r��iuM������ut�v-���]�� �4,׬m���F�fQ�఩� H��a��e��ڤ/،���mC��3 a�އ�U�"�҄��i4S����#ge|OL�Y)�5{}V���ec���I��"[�>�e}�嗣,.��ؚyi����]?�N0�֮��BXf�z���/��j[��-����f����.#��N�����t��l��a�f�t[F�g�����"]a�Y��(áR��&�,��[�@�M���$ν���w0�9���K�^1|�&�. �5��2$���z��P� ��%9|��`�>O������f2ñ+| ��5E"�,E͔iM����W$���J���h�m!�`F���ִav���� ��3J�*�*4C�ĉn8� �gtK�d!wd|��L�E��=���|�*Gi#���I��h논����"�RJ�m�'hTPK����~>��ߝ��τ�l����#x�.�evڟ�D��'Pƣt�PƜ�L���)O&q<��ߍ�R^��v��������jC/�Ƙ�\di�4�$�0�Irp���[Fߒ�~+3����������01Ɯ��c�ץ���9�����4�q��(�]A���Rӆ翀؝�&v��*�x��(`F��ga��g��n�>��>��ij�|kۑ���+2)�����ӪśL��ѯ��<����3���QC�Yr�2L�Dq���Ŭ�"���6]�����K�I��۪���تǠW�Uo]��S�k")��u���{ë��}�̇D"�hw�DPi�ٺt#w������|H)��} K�V��U(��t)Gov�kS�3�����"(���)1���б|ʣ`�1D�ߍx^{�c�Y�#�#}RrG���vɁ�q}:����X� L���A2����_��ǈuq�`J[8��}+�0!`��4�t�"Sel�O��uA^�%5f�1?!�9����c:ץT�� %Еڃp��)�Q_4@L���Gȫ�yJ:����]V�A$&!��t��S��W��֍��=�d+������t Iou�k��x(ڊD.���C �,�]D���b��5%�~�9���S��(L��V����v�|��\�����I�ܩ��LL�c^[iBk:e��"� �i� ��5Ug�.҉d=iVg(#�E;��BZ�x��k�g���JR��R>)ú2`w��V�g���f�h�m��M���}�t���J�l���MO��`�A��q�Vˎ�*1���c�O��Ίr�v����qx,$`9��W����,�I�U���3�7�)||I�����:o���.��Xҵ�(�"�f�ؚ�jЁ�5`��S+�Տ��j�CB�����Z �7$�\�M}�\�p}}T٫���Z���S��ztT��^��Pa�>����f�|���CwV��N@2����i�3}\ �>�]��W���0|�������˄�P�>N��^��l�ʁwچ�[���v�r�M��l�}�j���!��P�.�˥��00��4v�.2}�Lf�@p��tM��ԧ^8�E���92��~��.�鯮�Q�����C�j� ��ocTJ/~��/�tYak0���?��Z���ں��[���k9MW������~�w��]�6W��?Ḇ8�U��H��,:���u���HXhضk�U�U�g_����Nxr�Jp�TV��E�Y�k ��đ)��K�X�}b��J���J�Z�ԝ]���p ���M�rl�^�۶��\�*�C��7kz�e ��n�h�� Gj4f���U�(� �� ^&� �����S ~��3r�]6MY<��6���A_���^�!y�󄖨oʋ���M�h#R� �qS,���"B��; FDI���ç<��{ F 峜���4��3%�ފf�N�eȞ�P�\�ӆ�����.#]�"�aꏴ~��Tzn�*��ܕ�._�a|���\T����m/��c���Se�U�h�vm�ͻFK��fO���=������n���X��۰��uW�gK��|�hڰ�;�7�r�~��˶b�~�Z��"U!;���n� Mu� e����U�?+?�yӋƤ������Y�M:[�����8�7i}."�����}�v/��-����}��zqG^��xa��%~߼�����%1�y+�kF{������v�����^P�㯛6�'�ꂐeA��p�>�ޣ�\ޠ�y�q�E�\G�Z�l��/ b����j��u@����(F"~߸�cL�K%;�o�A�`,�2�E�w��O[c��G���C�~۱m����M����f�k�������V>)�WeQ�j����2=Pm�2���=���F�C_��N�ҫ��P*��0_�d8c�+���H�Y���~��e>`

**Comment by ophian** [comment]
Danke. Update ist online. Bitte bestätigen wenn ok. 
Dieses angehängte Geraffel ist sozusagen das, was encoded an Google geht oder von Google kommt? Wird das tasächlich einfach so ausgegeben?

**Comment by Pflegecraft** [comment]
Jo super läuft jetzt wie geschmiert :)
und ja das war wirklich die Ausgabe von der Seite ich habe auch nicht schlecht gestaunt so die ersten 9 Zeilen kann man ja wissen was gemeint ist aber danach uff :D
