### ISSUE TITLE
Free-Tags Installationsfehler

### ISSUE THREAD

**Issue by Pflegecraft** [ophian/additional_plugins#6]
Hallo ich bekomme seit dem neuen Serendipity Update einen 500 Error beim aufrufen der Hauptseite.
Apachelogs:
```....
[Mon Apr 18 09:23:08.158492 2022] [proxy_fcgi:error] [pid 1319009:tid 140294904174336] [client 108.162.242.29:13806] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'pflegecraft_db1.styx_entrytags' doesn't exist in /home/users/pflegecraft/www/blog/include/db/mysqli.inc.php:76\nStack trace:\n#0 /home/users/pflegecraft/www/blog/include/db/mysqli.inc.php(76): mysqli_query()\n#1 /home/users/pflegecraft/www/blog/plugins/serendipity_event_freetag/serendipity_event_freetag.php(2033): serendipity_db_query()\n#2 /home/users/pflegecraft/www/blog/plugins/serendipity_event_freetag/serendipity_event_freetag.php(1278): serendipity_event_freetag->frontend_fetch_showtag()\n#3 /home/users/pflegecraft/www/blog/include/plugin_api.inc.php(1144): serendipity_event_freetag->event_hook()\n#4 /home/users/pflegecraft/www/blog/include/functions_entries.inc.php(602): serendipity_plugin_api::hook_event()\n#5 /home/users/pflegecraft/www/blog/include/genpage.inc.php(51): serendipity_fetchEntry()\n#6 /home/users/pflegecraft/www/blog/include/functions_routing.inc.php(467): include('...')\n#7 /home/users/pflegecraft/www/blog/index.ph...', referer: https://pflegecraft.de/archives/6-Covid-19-Google-Maps.html
[Mon Apr 18 09:23:08.579981 2022] [proxy_fcgi:error] [pid 1309966:tid 140294912575232] [client 108.162.242.25:28232] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'pflegecraft_db1.styx_entrytags' doesn't exist in /home/users/pflegecraft/www/blog/include/db/mysqli.inc.php:76\nStack trace:\n#0 /home/users/pflegecraft/www/blog/include/db/mysqli.inc.php(76): mysqli_query()\n#1 /home/users/pflegecraft/www/blog/plugins/serendipity_event_freetag/serendipity_event_freetag.php(2033): serendipity_db_query()\n#2 /home/users/pflegecraft/www/blog/plugins/serendipity_event_freetag/serendipity_event_freetag.php(1278): serendipity_event_freetag->frontend_fetch_showtag()\n#3 /home/users/pflegecraft/www/blog/include/plugin_api.inc.php(1144): serendipity_event_freetag->event_hook()\n#4 /home/users/pflegecraft/www/blog/include/functions_entries.inc.php(381): serendipity_plugin_api::hook_event()\n#5 /home/users/pflegecraft/www/blog/include/genpage.inc.php(148): serendipity_fetchEntries()\n#6 /home/users/pflegecraft/www/blog/include/functions_routing.inc.php(22): include('...')\n#7 /home/users/pflegecraft/www/blog/index....', referer: https://pflegecraft.de/
```

Hergenesweise:
1. Free-Tags Plugin installiert.
2. Bleibt bei Daten wurden erfolgreich heruntergeladen hängen
3. Manuelles zurück gehen.
4. Erscheinen der 500er Meldung beim aufrufen meines Blogs.

**Comment by ophian** [comment]
Das ist immer derselbe Fehler: `Table 'pflegecraft_db1.styx_entrytags' doesn't exist`
Ist das eine komplett neue Styx und komplett neue freetags Installation?
Ansonsten kann ich mir nur vorstellen, dass du versucht hast dein altes Serendipity wiederherzustellen und dabei versehentlich Einstellungen übernommen hast, die freetag beim install vorgaukelten bereits installiert zu sein (zb in styx_plugins u.ev.a.) und deswegen eine oder beide freetag Tabellen fehlen..

**Comment by ophian** [comment]
Oh YEAH! One of these days... thanks for finding this inconsistency!
I found your issue. Fixed in freetag 5.18. Its because it tries to check an (non-)existing table first to know it has to get installed or not.
The Serendipity API is very clear on how to use such a query. But Developers are lazy and in the old days it did not matter!
Wait ~12hours or use the Spartacus plugin config trick (_just save it (again)_) to delete the cached XML files and to order new ones when you hit `plugin updates`. Prior check you don't have the `styx_entrytags` and the `styx_tagkeywords` database tables and you have **uninstalled** a possible announced freetag plugin in your backend pluginlist.
