### ISSUE TITLE
event_dsgvo_gdpr Error

### ISSUE THREAD

**Issue by Pflegecraft** [ophian/additional_plugins#7]
Hi i found a Error on Php 8.2 with Serenditpity Styx 4.0.1 

`Warning: Undefined array key "transmits_user_input" in /home/users/pflegecraft/www/blog/plugins/serendipity_event_dsgvo_gdpr/serendipity_event_dsgvo_gdpr.php: 283.
Administrative Login Error Warning only - not seen by visitors! Send us a note what happened where and when, please.`
 in serendipity_event_dsgvo_gdpr Plugin

My Blog: https://pflegecraft.de

Greetz
Florian "Pflegecraft"

**Comment by ophian** [comment]
Thanks. It should already be defined by the $propbag at line 76 and be set default to boolean false.  If the others like `stores_ip` or `uses_ip` don't error why should this one? _Hmm..._

I could be that some plugin does not set this variable.  Please give me a list of all event Plugins in their order.

Or you better store `var_dump($legal);` on line 204, right after `$legal = $bag->get('legal');` save and re-run that page and then investigate the output by right click and "Seiten Quelltext anzeigen" of your browser, which then (scroll down a little bit)  has the stored legal plugin long array dump of all used plugins in a readable format. Plugins that do not have a legal property just throw `NULL`. Copy it all and please paste it here. After that remove the debug again.

**Comment by Pflegecraft** [comment]
thanks for your Fix this was it :) sorry i am in School and Homecare.
